import config from '../config.js';

const companies = [
    '1win', 'betway', 'sportybet', 'premierbet', 'betika', 'wasafibet',
    '888sport', 'parimatch', '22bet', 'melbet', 'mozzart', 'mbet',
    'meridianbet', 'gsb', 'bet365', 'megapari'
];

export default {
    command: 'aviatorhelp',
    aliases: ['avhelp', 'avmanual'],
    category: 'fun',
    description: 'Show the complete VIP Aviator manual with strategies and tips',
    usage: '.aviatorhelp',
    async handler(sock, message, args, context) {
        const { chatId, channelInfo } = context;
        const prefix = config.prefixes?.[0] || '.';
        const imageUrl = 'https://raw.githubusercontent.com/stanytz378/stanyimagesservers/refs/heads/main/IMG_1424.jpeg';

        // Send an image first (optional)
        await sock.sendMessage(chatId, {
            image: { url: imageUrl },
            caption: `╭── • 🥀 • ──╮\n  ᴠɪᴘ ᴀᴠɪᴀᴛᴏʀ ᴍᴀɴᴜᴀʟ\n╰── • 🥀 • ──╯\n\n_Read the manual below to learn how to play._`,
            ...channelInfo
        }, { quoted: message });

        const manual = `╭─── • 🥀 • ───╮
   ᴠɪᴘ ᴀᴠɪᴀᴛᴏʀ ᴍᴀɴᴜᴀʟ
╰─── • 🥀 • ───╯

━━━━━━━━━━━━━━━━━━━━━━━━━
🔰 *HOW TO USE VIP SIGNALS*
━━━━━━━━━━━━━━━━━━━━━━━━━

1️⃣ *View this manual*  
   Use ${prefix}aviatorhelp to display this guide.

2️⃣ *Request a prediction for a specific company*  
   Use ${prefix}aviator <company>  
   Example: ${prefix}aviator 1win  
   → Generates a prediction for 1win with expected burst, confidence, and strategy.

   To see all supported companies, check the list at the end.

3️⃣ *How each prediction is delivered*  
   - Contains:
     • Company name
     • Expected burst multiplier (e.g., 2.35x)
     • Confidence percentage (75‑99%)
     • Recommended action
   - Use the strategies below to act on the signal.

━━━━━━━━━━━━━━━━━━━━━━━━━
🎯 *PLAYING STRATEGIES (with real examples)*
━━━━━━━━━━━━━━━━━━━━━━━━━

┌─── 🛡️ *STRATEGY 1: CONSERVATIVE (Low Risk)*
│  • Bet amount: 1,000 TZS
│  • Target: 1.5x – 2.0x
│  • How: When you see a signal for a company, open that site.
│         Place your bet. Watch the multiplier live.
│         As soon as it passes 1.5x, cash out.
│  • Example:
│      - Signal: 1win – expected 2.3x, confidence 88%
│      - You bet 1,000 TZS on 1win.
│      - Multiplier reaches 1.7x → you cash out.
│      - Profit = 1,000 × (1.7 – 1) = 700 TZS.
│  • Risk: Very low. You win small but consistently.
└────────────────────────

┌─── ⚖️ *STRATEGY 2: MODERATE (Balanced)*
│  • Bet amount: 2,000 TZS
│  • Target: 3.0x – 5.0x
│  • How: Look for signals with confidence >85% and analysis mentioning
│         "two consecutive low rounds" or "green spike". Place bet and
│         let it ride until 3.0x, then cash out.
│  • Example:
│      - Signal: betpawa – expected 4.2x, confidence 92%
│      - You bet 2,000 TZS on betpawa.
│      - Multiplier hits 3.8x → cash out.
│      - Profit = 2,000 × (3.8 – 1) = 5,600 TZS.
│  • Risk: Medium. You may lose some rounds, but wins cover losses.
└────────────────────────

┌─── 💎 *STRATEGY 3: AGGRESSIVE (High Risk / High Reward)*
│  • Bet amount: 500 TZS (small)
│  • Target: 10.0x – 20.0x
│  • How: Use only when analysis says "High reward potential" or
│         "Pattern matches previous winning rounds". Bet small and
│         hold until a very high multiplier.
│  • Example:
│      - Signal: sportybet – expected 15.7x, confidence 79%
│      - You bet 500 TZS on sportybet.
│      - Multiplier climbs to 12.4x → cash out.
│      - Profit = 500 × (12.4 – 1) = 5,700 TZS.
│  • Risk: High. Most rounds will crash early, but one big win can
│         give massive profit.
└────────────────────────

━━━━━━━━━━━━━━━━━━━━━━━━━
🧠 *VIP PRO TIPS*
━━━━━━━━━━━━━━━━━━━━━━━━━
✓ Always wait for the full signal – don't rush.
✓ Use a stop‑loss: if you lose 3 signals in a row, take a break.
✓ Keep track of your wins/losses with a small notebook.
✓ These signals are generated by advanced algorithms – treat them as
  high‑probability predictions, not guarantees.
✓ Play responsibly – never bet more than you can afford to lose.

━━━━━━━━━━━━━━━━━━━━━━━━━
📋 *SUPPORTED COMPANIES*
━━━━━━━━━━━━━━━━━━━━━━━━━
${companies.map(c => '• ' + c).join('\n')}

_🥀 Trust the shadows, not the pilot. Good luck, VIP._`;

        await sock.sendMessage(chatId, {
            text: manual,
            contextInfo: {
                isForwarded: true,
                forwardedNewsletterMessageInfo: {
                    newsletterJid: config.newsletterJid || '120363404317544295@newsletter',
                    newsletterName: config.botName || 'ᴵ ᴬᴹ ᴸᴱᴳᴱᴺᴰ'
                }
            }
        }, { quoted: message });
    }
};